### ISSUE TITLE
2023 update on the horizon?

### ISSUE THREAD

**Issue by bornright** [RemiArnaud/OpenCOLLADA#7]
I was so excited to see the 2022 drop, hoping it might work in 2023.

+1 from another hopeful user awaiting a new DLE for 2023.  Exporting to SketchUp without it is useless.  Such a valuable script for me.

**Comment by RemiArnaud** [comment]
https://github.com/RemiArnaud/OpenCOLLADA/releases/tag/v1.6.71-max
