### ISSUE TITLE
3Ds 2024?

### ISSUE THREAD

**Issue by xMaveRiicK** [RemiArnaud/OpenCOLLADA#8]
Is possible to get the plugin compiled for the newest MAX version? Would be very nice to have it :)

**Comment by cyber-speed** [comment]
I agree, for 2023 as well as 2024, if I'd know how to I'd compile them myself.

**Comment by RemiArnaud** [comment]
https://github.com/RemiArnaud/OpenCOLLADA/releases/tag/v1.6.71-max
